"""initial

Revision ID: 18b15227f44e
Revises: 
Create Date: 2026-08-06 16:22:10.863136+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types


# ---------------------------------------------------------------------------
# Revision identifiers (used by Alembic)
# ---------------------------------------------------------------------------
revision: str = '18b15227f44e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the schema changes defined in this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospitals',
    sa.Column('hospital_name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('available_beds', sa.Integer(), nullable=False),
    sa.Column('icu_beds', sa.Integer(), nullable=False),
    sa.Column('ventilators', sa.Integer(), nullable=False),
    sa.Column('ambulances', sa.Integer(), nullable=False),
    sa.Column('blood_units', sa.Integer(), nullable=False),
    sa.Column('oxygen_units', sa.Integer(), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('ambulances >= 0', name='ck_hospital_ambulances_non_negative'),
    sa.CheckConstraint('available_beds >= 0', name='ck_hospital_available_beds_non_negative'),
    sa.CheckConstraint('blood_units >= 0', name='ck_hospital_blood_units_non_negative'),
    sa.CheckConstraint('icu_beds >= 0', name='ck_hospital_icu_beds_non_negative'),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name='ck_hospital_latitude_range'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name='ck_hospital_longitude_range'),
    sa.CheckConstraint('oxygen_units >= 0', name='ck_hospital_oxygen_units_non_negative'),
    sa.CheckConstraint('ventilators >= 0', name='ck_hospital_ventilators_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_created_at'), 'hospitals', ['created_at'], unique=False)
    op.create_index(op.f('ix_hospitals_hospital_name'), 'hospitals', ['hospital_name'], unique=False)
    op.create_index(op.f('ix_hospitals_is_deleted'), 'hospitals', ['is_deleted'], unique=False)
    op.create_index('ix_hospitals_lat_lon', 'hospitals', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_hospitals_latitude'), 'hospitals', ['latitude'], unique=False)
    op.create_index(op.f('ix_hospitals_longitude'), 'hospitals', ['longitude'], unique=False)
    op.create_table('shelters',
    sa.Column('shelter_name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('current_occupancy', sa.Integer(), nullable=False),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('capacity >= 0', name='ck_shelter_capacity_non_negative'),
    sa.CheckConstraint('current_occupancy <= capacity', name='ck_shelter_occupancy_within_capacity'),
    sa.CheckConstraint('current_occupancy >= 0', name='ck_shelter_current_occupancy_non_negative'),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name='ck_shelter_latitude_range'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name='ck_shelter_longitude_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelters_created_at'), 'shelters', ['created_at'], unique=False)
    op.create_index(op.f('ix_shelters_is_deleted'), 'shelters', ['is_deleted'], unique=False)
    op.create_index('ix_shelters_lat_lon', 'shelters', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_shelters_latitude'), 'shelters', ['latitude'], unique=False)
    op.create_index(op.f('ix_shelters_longitude'), 'shelters', ['longitude'], unique=False)
    op.create_index(op.f('ix_shelters_shelter_name'), 'shelters', ['shelter_name'], unique=False)
    op.create_table('users',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('GOVERNMENT', 'NGO', 'VOLUNTEER', 'HOSPITAL', 'CITIZEN', name='role_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_district'), 'users', ['district'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_role_district', 'users', ['role', 'district'], unique=False)
    op.create_index('ix_users_role_is_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('disasters',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('disaster_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='disaster_severity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('REPORTED', 'VERIFIED', 'RESOURCE_ALLOCATED', 'RESCUE_ONGOING', 'RESOLVED', name='disaster_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('reported_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name='ck_disaster_latitude_range'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name='ck_disaster_longitude_range'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disasters_created_at'), 'disasters', ['created_at'], unique=False)
    op.create_index(op.f('ix_disasters_disaster_type'), 'disasters', ['disaster_type'], unique=False)
    op.create_index(op.f('ix_disasters_district'), 'disasters', ['district'], unique=False)
    op.create_index('ix_disasters_district_status', 'disasters', ['district', 'status'], unique=False)
    op.create_index(op.f('ix_disasters_is_deleted'), 'disasters', ['is_deleted'], unique=False)
    op.create_index('ix_disasters_lat_lon', 'disasters', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_disasters_latitude'), 'disasters', ['latitude'], unique=False)
    op.create_index(op.f('ix_disasters_longitude'), 'disasters', ['longitude'], unique=False)
    op.create_index(op.f('ix_disasters_reported_by'), 'disasters', ['reported_by'], unique=False)
    op.create_index(op.f('ix_disasters_severity'), 'disasters', ['severity'], unique=False)
    op.create_index('ix_disasters_severity_status', 'disasters', ['severity', 'status'], unique=False)
    op.create_index(op.f('ix_disasters_status'), 'disasters', ['status'], unique=False)
    op.create_index('ix_disasters_type_severity', 'disasters', ['disaster_type', 'severity'], unique=False)
    op.create_table('notifications',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='notification_priority', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('recipient_role', sa.Enum('GOVERNMENT', 'NGO', 'VOLUNTEER', 'HOSPITAL', 'CITIZEN', name='role_enum_notif', native_enum=False), nullable=True),
    sa.Column('recipient_id', sa.Uuid(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_priority'), 'notifications', ['priority'], unique=False)
    op.create_index('ix_notifications_priority_is_read', 'notifications', ['priority', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_id'), 'notifications', ['recipient_id'], unique=False)
    op.create_index('ix_notifications_recipient_is_read', 'notifications', ['recipient_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_role'), 'notifications', ['recipient_role'], unique=False)
    op.create_index('ix_notifications_role_priority', 'notifications', ['recipient_role', 'priority'], unique=False)
    op.create_table('emergency_reports',
    sa.Column('reporter_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('disaster_type', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reported_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('linked_disaster_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('latitude IS NULL OR (latitude >= -90 AND latitude <= 90)', name='ck_report_latitude_range'),
    sa.CheckConstraint('longitude IS NULL OR (longitude >= -180 AND longitude <= 180)', name='ck_report_longitude_range'),
    sa.ForeignKeyConstraint(['linked_disaster_id'], ['disasters.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emergency_reports_created_at'), 'emergency_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_emergency_reports_disaster_type'), 'emergency_reports', ['disaster_type'], unique=False)
    op.create_index(op.f('ix_emergency_reports_is_deleted'), 'emergency_reports', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_emergency_reports_latitude'), 'emergency_reports', ['latitude'], unique=False)
    op.create_index(op.f('ix_emergency_reports_linked_disaster_id'), 'emergency_reports', ['linked_disaster_id'], unique=False)
    op.create_index(op.f('ix_emergency_reports_longitude'), 'emergency_reports', ['longitude'], unique=False)
    op.create_index(op.f('ix_emergency_reports_reported_at'), 'emergency_reports', ['reported_at'], unique=False)
    op.create_index(op.f('ix_emergency_reports_reported_by_user_id'), 'emergency_reports', ['reported_by_user_id'], unique=False)
    op.create_index('ix_reports_disaster_reported_at', 'emergency_reports', ['linked_disaster_id', 'reported_at'], unique=False)
    op.create_index('ix_reports_lat_lon', 'emergency_reports', ['latitude', 'longitude'], unique=False)
    op.create_table('predictions',
    sa.Column('prediction', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('input_features', app.models.types.AutoJSON(), nullable=True),
    sa.Column('predicted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disaster_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0', name='ck_prediction_confidence_range'),
    sa.ForeignKeyConstraint(['disaster_id'], ['disasters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_created_at'), 'predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_predictions_disaster_id'), 'predictions', ['disaster_id'], unique=False)
    op.create_index('ix_predictions_disaster_predicted_at', 'predictions', ['disaster_id', 'predicted_at'], unique=False)
    op.create_index(op.f('ix_predictions_is_deleted'), 'predictions', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_predictions_predicted_at'), 'predictions', ['predicted_at'], unique=False)
    op.create_table('resources',
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ALLOCATED', 'IN_TRANSIT', 'CONSUMED', name='resource_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('assigned_disaster', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.CheckConstraint('available_quantity <= quantity', name='ck_resource_available_lte_total'),
    sa.CheckConstraint('available_quantity >= 0', name='ck_resource_available_quantity_non_negative'),
    sa.CheckConstraint('quantity >= 0', name='ck_resource_quantity_non_negative'),
    sa.ForeignKeyConstraint(['assigned_disaster'], ['disasters.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_assigned_disaster'), 'resources', ['assigned_disaster'], unique=False)
    op.create_index(op.f('ix_resources_created_at'), 'resources', ['created_at'], unique=False)
    op.create_index(op.f('ix_resources_is_deleted'), 'resources', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    op.create_index(op.f('ix_resources_status'), 'resources', ['status'], unique=False)
    op.create_index('ix_resources_status_disaster', 'resources', ['status', 'assigned_disaster'], unique=False)
    op.create_index('ix_resources_type_status', 'resources', ['resource_type', 'status'], unique=False)
    op.create_table('assignments',
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('volunteer_id', sa.Uuid(), nullable=True),
    sa.Column('ngo_id', sa.Uuid(), nullable=True),
    sa.Column('hospital_id', sa.Uuid(), nullable=True),
    sa.Column('disaster_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='assignment_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['disaster_id'], ['disasters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ngo_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_created_at'), 'assignments', ['created_at'], unique=False)
    op.create_index(op.f('ix_assignments_disaster_id'), 'assignments', ['disaster_id'], unique=False)
    op.create_index('ix_assignments_disaster_status', 'assignments', ['disaster_id', 'status'], unique=False)
    op.create_index(op.f('ix_assignments_hospital_id'), 'assignments', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_assignments_is_deleted'), 'assignments', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_assignments_ngo_id'), 'assignments', ['ngo_id'], unique=False)
    op.create_index(op.f('ix_assignments_resource_id'), 'assignments', ['resource_id'], unique=False)
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_index(op.f('ix_assignments_volunteer_id'), 'assignments', ['volunteer_id'], unique=False)
    op.create_index('ix_assignments_volunteer_status', 'assignments', ['volunteer_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema changes defined in this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assignments_volunteer_status', table_name='assignments')
    op.drop_index(op.f('ix_assignments_volunteer_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_resource_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_ngo_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_is_deleted'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_hospital_id'), table_name='assignments')
    op.drop_index('ix_assignments_disaster_status', table_name='assignments')
    op.drop_index(op.f('ix_assignments_disaster_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_created_at'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index('ix_resources_type_status', table_name='resources')
    op.drop_index('ix_resources_status_disaster', table_name='resources')
    op.drop_index(op.f('ix_resources_status'), table_name='resources')
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_is_deleted'), table_name='resources')
    op.drop_index(op.f('ix_resources_created_at'), table_name='resources')
    op.drop_index(op.f('ix_resources_assigned_disaster'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_predictions_predicted_at'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_is_deleted'), table_name='predictions')
    op.drop_index('ix_predictions_disaster_predicted_at', table_name='predictions')
    op.drop_index(op.f('ix_predictions_disaster_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_created_at'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_reports_lat_lon', table_name='emergency_reports')
    op.drop_index('ix_reports_disaster_reported_at', table_name='emergency_reports')
    op.drop_index(op.f('ix_emergency_reports_reported_by_user_id'), table_name='emergency_reports')
    op.drop_index(op.f('ix_emergency_reports_reported_at'), table_name='emergency_reports')
    op.drop_index(op.f('ix_emergency_reports_longitude'), table_name='emergency_reports')
    op.drop_index(op.f('ix_emergency_reports_linked_disaster_id'), table_name='emergency_reports')
    op.drop_index(op.f('ix_emergency_reports_latitude'), table_name='emergency_reports')
    op.drop_index(op.f('ix_emergency_reports_is_deleted'), table_name='emergency_reports')
    op.drop_index(op.f('ix_emergency_reports_disaster_type'), table_name='emergency_reports')
    op.drop_index(op.f('ix_emergency_reports_created_at'), table_name='emergency_reports')
    op.drop_table('emergency_reports')
    op.drop_index('ix_notifications_role_priority', table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_role'), table_name='notifications')
    op.drop_index('ix_notifications_recipient_is_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_id'), table_name='notifications')
    op.drop_index('ix_notifications_priority_is_read', table_name='notifications')
    op.drop_index(op.f('ix_notifications_priority'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_disasters_type_severity', table_name='disasters')
    op.drop_index(op.f('ix_disasters_status'), table_name='disasters')
    op.drop_index('ix_disasters_severity_status', table_name='disasters')
    op.drop_index(op.f('ix_disasters_severity'), table_name='disasters')
    op.drop_index(op.f('ix_disasters_reported_by'), table_name='disasters')
    op.drop_index(op.f('ix_disasters_longitude'), table_name='disasters')
    op.drop_index(op.f('ix_disasters_latitude'), table_name='disasters')
    op.drop_index('ix_disasters_lat_lon', table_name='disasters')
    op.drop_index(op.f('ix_disasters_is_deleted'), table_name='disasters')
    op.drop_index('ix_disasters_district_status', table_name='disasters')
    op.drop_index(op.f('ix_disasters_district'), table_name='disasters')
    op.drop_index(op.f('ix_disasters_disaster_type'), table_name='disasters')
    op.drop_index(op.f('ix_disasters_created_at'), table_name='disasters')
    op.drop_table('disasters')
    op.drop_index('ix_users_role_is_active', table_name='users')
    op.drop_index('ix_users_role_district', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_district'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shelters_shelter_name'), table_name='shelters')
    op.drop_index(op.f('ix_shelters_longitude'), table_name='shelters')
    op.drop_index(op.f('ix_shelters_latitude'), table_name='shelters')
    op.drop_index('ix_shelters_lat_lon', table_name='shelters')
    op.drop_index(op.f('ix_shelters_is_deleted'), table_name='shelters')
    op.drop_index(op.f('ix_shelters_created_at'), table_name='shelters')
    op.drop_table('shelters')
    op.drop_index(op.f('ix_hospitals_longitude'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_latitude'), table_name='hospitals')
    op.drop_index('ix_hospitals_lat_lon', table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_is_deleted'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_hospital_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_created_at'), table_name='hospitals')
    op.drop_table('hospitals')
    # ### end Alembic commands ###
