"""add_governance_routing_csr_tables

Revision ID: 1503c5f41b57
Revises: 18b15227f44e
Create Date: 2026-08-08 05:01:19.631972+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# ---------------------------------------------------------------------------
# Revision identifiers (used by Alembic)
# ---------------------------------------------------------------------------
revision: str = '1503c5f41b57'
down_revision: Union[str, None] = '18b15227f44e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the schema changes defined in this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the schema changes defined in this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
